---
title: "Reproducible code report - VANESSA-DAM-CRA"
author: "Produced with [VANESSA-DAM](https://github.com/orijitghosh/VANESSA-DAM) on `r Sys.Date()`"
github: {user: orijitghosh, repo: VANESSA-DAM}
output:
  html_document:
    theme: journal
    highlight: haddock
params:
  meta: NA
  wd: NA
  modtau: NA
  ldperiod: NA
  min: NA
  light: NA
  genotype: NA
  replicate: NA
  remove: NA
  start: NA
  end: NA
  permethod: NA
  ul: NA
  ll: NA
# Reproducible code report - VANESSA-DAM-CRA   
---

### All parameters used in the shiny app for analysis.
```{r}
params$meta
params$wd
params$modtau
params$ldperiod
params$min
params$light
params$genotype
params$replicate
params$remove
params$start
params$end
params$permethod
params$ul
params$ll
```

### **Set working directory of R to where your Metadata file and Monitor files are (in this case they have to be in the same directory). Replace all params$XXXX with the values mentioned above (values you have used in the shiny app).**

### Load all needed libraries:
```
library(data.table)
library(ggetho)
library(zeitgebr)
library(ggplot2)
library(ggridges)
library(readr)
library(damr)
library(sleepr)
library(behavr)
library(dplyr)
library(tidyr)
```

### Do data pre-processing:
```
setwd(params$wd)
metadata <- fread("params$meta")
    metadata <- na.omit(metadata)
    metadata_proc <- link_dam_metadata(metadata, result_dir = params$wd)
    dt <- load_dam(metadata_proc)
        dt[, moving := activity > 0]
        dt_curated <- curate_dead_animals(dt)
        lifespan_dt <- dt_curated[, .(lifespan = max(t)), by = id]
        valid_ids <- lifespan_dt[lifespan > days(params$remove), id]
        dt_curated <- dt_curated[id %in% valid_ids]
        dt_curated <- dt_curated[t %between% c(days(params$start), days(params$end))]
        dt_curated <- dt_curated[, Day := (t / days(1)), by = id]
        dt_curated$Day <- ceiling(dt_curated$Day)
        dt_curated[, 5][dt_curated[, 5] == params$start] <- params$start + 1
        setkey(dt_curated, Day, id)
        dt_curated[, normact := (activity / sum(activity)) * 100, by = .(id, Day)]
        setkey(dt_curated, id)
        setbehavr(dt_curated, metadata_proc)
        dt_curated[, uid := 1:.N, meta = T]
        dt_curated[, .(id, uid), meta = T]
```

### Theme configuration for figures:
```
    My_Theme <- theme(
      title = element_text(size = 10, face = "bold"),
      axis.title.x = element_text(size = 10, face = "bold"),
      axis.text.x = element_text(size = 8),
      axis.title.y = element_text(size = 10, face = "bold"),
      axis.text.y = element_text(size = 8),
      legend.text = element_text(size = 8),
      legend.position = "right",
      panel.background = element_rect(fill = "white"),
      panel.grid.major = element_line(
        size = 0.125,
        linetype = "solid",
        colour = "grey"
      ),
      panel.grid.minor = element_line(
        size = 0.0625,
        linetype = "solid",
        colour = "grey"
      ),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(
        colour = "black",
        size = 8,
        color = "black",
        face = "bold"
      ),
    )

    My_Theme1 <- theme(
      title = element_text(size = 6, face = "bold"),
      axis.title.x = element_text(size = 4, face = "bold"),
      axis.text.x = element_text(size = 3),
      axis.title.y = element_text(size = 3, face = "bold"),
      axis.text.y = element_text(size = 3),
      legend.text = element_text(size = 3),
      legend.position = "right",
      panel.background = element_rect(fill = "white"),
      panel.grid.major = element_line(
        size = 0.025,
        linetype = "solid",
        colour = "grey"
      ),
      panel.grid.minor = element_line(
        size = 0.0125,
        linetype = "solid",
        colour = "grey"
      ),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(
        colour = "black",
        size = 3,
        color = "black",
        face = "bold"
      ),
    )
```
### Do calculations for periodogram:
##### If `params$permethod` is "Chi-square" - 
```
per_xsq_dt_chi_sq <- periodogram(activity,
              dt_curated,
              period_range = c(hours(params$ll), hours(params$ul)),
              FUN = chi_sq_periodogram
            )
            per_xsq_dt_chi_sq <- find_peaks(per_xsq_dt_chi_sq)
```
##### If `params$permethod` is "Autocorrelation" - 
```
per_xsq_dt_chi_sq <- periodogram(activity,
              dt_curated,
              period_range = c(hours(params$ll), hours(params$ul)),
              FUN = ac_periodogram
            )
            per_xsq_dt_chi_sq <- find_peaks(per_xsq_dt_chi_sq)
```
##### If `params$permethod` is "Lomb-Scargle" -
```
per_xsq_dt_chi_sq <- periodogram(activity,
              dt_curated,
              period_range = c(hours(params$ll), hours(params$ul)),
              FUN = ls_periodogram
            )
            per_xsq_dt_chi_sq <- find_peaks(per_xsq_dt_chi_sq)
```
##### If `params$permethod` is "CWT" -
```
per_xsq_dt_chi_sq <- periodogram(activity,
              dt_curated,
              period_range = c(hours(params$ll), hours(params$ul)),
              FUN = cwt_periodogram
            )
            per_xsq_dt_chi_sq <- find_peaks(per_xsq_dt_chi_sq)
```
### Choose rhythmic individuals only
```
          per_xsq_dt_new <- per_xsq_dt_chi_sq[peak == 1, id]
            dt_curated <<- dt_curated[id %in% per_xsq_dt_new]
            per_xsq_dt_chi_sq <<-
              per_xsq_dt_chi_sq[id %in% per_xsq_dt_new]
```
### Plot periodograms with peaks:
```
p <- ggperio(per_xsq_dt_chi_sq) +
              geom_line(aes(group = id, colour = genotype), size = 1) +
              geom_peak(peak_rank = 1:2, col = "blue") +
              geom_line(aes(y = signif_threshold), colour = "red") +
              facet_wrap(~ genotype + uid + replicate, ncol = 4, scales = "free_y") +
              My_Theme
              ggsave(p, filename = "Plot periodograms with peaks.png", type = "cairo",height = 30,
       width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is number of genotypes
###############and width = 10
```
### Plot average periodograms:
```
p <- ggperio(
              per_xsq_dt_chi_sq,
              aes(x = period, y = power - signif_threshold, colour = genotype)
            ) +
              stat_pop_etho() +
              facet_wrap(~replicate, ncol = 1, scales = "free_y") +
              My_Theme
              ggsave(p, filename = "Plot average periodograms.png", type = "cairo",height = 5,
       width = 10, dpi = 600, units = "in")    ###############height = 5*n where n is number of replicates
###############and width = 10
```
### Plot period violin plots:
```
summary_dt <- rejoin(per_xsq_dt_chi_sq[peak == 1])
            p <- ggplot(summary_dt, aes(genotype, period, fill = genotype)) +
              # geom_boxplot(outlier.colour = NA) +
              geom_jitter(aes(size = power - signif_threshold), alpha = .5, position = position_jitter(0.15)) +
              geom_violin(aes(color = genotype, fill = genotype), trim = TRUE, alpha = 0.5) +
              stat_summary(fun = mean, geom = "point", aes(color = genotype), size = 3, shape = 23) +
              stat_summary(aes(label = round((..y.. / 3600), 2), color = genotype), fun = mean, geom = "text", size = 5, vjust = -0.5) +
              facet_wrap(~replicate, ncol = 1) +
              scale_y_hours(name = "Period") +
              My_Theme
              ggsave(p, filename = "Plot period violin plots.png", type = "cairo",height = 5,
       width = 10, dpi = 600, units = "in")    ###############height = 5*n where n is number of replicates
###############and width = 10
```
### Plot period distributions:
```
summary_dt <- rejoin(per_xsq_dt_chi_sq[peak == 1])
            p <- ggplot(summary_dt, aes((period / 3600), genotype, color = genotype, fill = genotype)) +
              geom_density_ridges(
                scale = 1, rel_min_height = 0.01, jittered_points = TRUE,
                position = position_points_jitter(width = 0.2, height = 0),
                point_shape = "|", point_size = 8, point_alpha = 1, alpha = .7
              ) +
              scale_y_discrete(expand = c(0, 0)) + # will generally have to set the `expand` option
              scale_x_continuous(expand = c(0, 0)) + # for both axes to remove unneeded padding
              coord_cartesian(clip = "off") + # to avoid clipping of the very top of the top ridgeline
              labs(x = "Period (h)", y = "Genotype") +
              My_Theme
              ggsave(p, filename = "Plot period distributions.png", type = "cairo",height = 6,
       width = 10, dpi = 600, units = "in")    ###############height = 6*n where n is number of replicates
###############and width = 10
```
### Plot all ethograms:
```
p <- alletho <-
                ggetho(dt,
                  aes(z = activity),
                  summary_time_window = mins(params$min)
                ) +
                stat_ld_annotations(
                  height = 0.01,
                  l_duration = hours(params$light),
                  period = hours(params$ldperiod)
                ) +
                stat_tile_etho() +
                My_Theme +
                scale_fill_distiller(palette = "Blues")
              alletho
              ggsave(p, filename = "Plot all ethograms.png", type = "cairo",height = 30,
       width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is number of genotypes
###############and width = 10
```
### Plot all actograms:
```
p <- alletho <-
            ggetho(dt, aes(z = activity), summary_time_window = mins(params$min)) +
            stat_ld_annotations(
              height = 0.005,
              alpha = 0.05,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_bar_tile_etho() +
            My_Theme
          alletho
          ggsave(p, filename = "Plot all actograms.png", type = "cairo",height = 30,
       width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is number of genotypes
###############and width = 10
```
### Plot curated ethograms:
```
p <- ggetho(dt_curated,
            aes(z = activity),
            summary_time_window = mins(params$min)
          ) +
            stat_ld_annotations(
              height = 0.01,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_tile_etho() +
            My_Theme +
            scale_fill_distiller(palette = "Blues")
          ggsave(p, filename = "Plot curated ethograms.png", type = "cairo",height = 30,
       width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is number of genotypes
###############and width = 10
```
### Plot curated actograms:
```
p <- alletho <-
            ggetho(dt_curated,
              aes(z = activity),
              summary_time_window = mins(params$min)
            ) +
            stat_ld_annotations(
              height = 0.005,
              alpha = 0.05,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_bar_tile_etho() +
            My_Theme
          alletho
          ggsave(p, filename = "Plot curated actograms.png", type = "cairo",height = 30,
       width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is number of genotypes
###############and width = 10
```
### Plot raw batch actograms:
```
p <- ggetho(
            dt_curated,
            aes(x = t, z = activity),
            multiplot = 2,
            multiplot_period = hours(params$modtau),
            summary_time_window = mins(params$min)
          ) + ### can change to activity if raw needed or keep it normact
            stat_ld_annotations(
              height = 1,
              alpha = 0.05,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_bar_tile_etho() +
            facet_wrap(~ genotype + replicate, ncol = 1, scales = "free_y") +
            My_Theme1
            ggsave(p, filename = "Plot raw batch actograms.png", type = "cairo",height = 18,
       width = 10, dpi = 600, units = "in")    ###############height = 6*n where n is number of genotypes
###############and width = 10
```
### Plot normalized batch actograms:
```
p <- ggetho(
            dt_curated,
            aes(x = t, z = normact),
            multiplot = 2,
            multiplot_period = hours(params$modtau),
            summary_time_window = mins(params$min)
          ) + ### can change to activity if raw needed or keep it normact
            stat_ld_annotations(
              height = 1,
              alpha = 0.05,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_bar_tile_etho() +
            facet_wrap(~ genotype + replicate, ncol = 1, scales = "free_y") +
            My_Theme1
            ggsave(p, filename = "Plot normalized batch actograms.png", type = "cairo",height = 18,
       width = 10, dpi = 600, units = "in")    ###############height = 6*n where n is number of genotypes
###############and width = 10
```
### Plot all raw actograms:
```
p <- ggetho(
            dt_curated,
            aes(z = activity),
            multiplot = 2,
            multiplot_period = hours(params$modtau),
            summary_time_window = mins(params$min)
          ) + ### can change to activity if raw needed or keep it normact
            stat_ld_annotations(
              height = 1,
              alpha = 0.05,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_bar_tile_etho() +
            facet_wrap(~ genotype + uid + replicate, ncol = 4, scales = "free_y") +
            theme(strip.background = element_rect(fill = "red")) +
            theme(strip.text = element_text(colour = "white")) +
            My_Theme
            ggsave(p, filename = "Plot all raw actograms.png", type = "cairo",height = 33,
       width = 10, dpi = 600, units = "in")    ###############height = 11*n where n is number of genotypes
###############and width = 10
```
### Plot all normalized actograms:
```
p <- ggetho(
            dt_curated,
            aes(z = normact),
            multiplot = 2,
            multiplot_period = hours(params$modtau),
            summary_time_window = mins(params$min)
          ) + ### can change to activity if raw needed or keep it normact
            stat_ld_annotations(
              height = 1,
              alpha = 0.05,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_bar_tile_etho() +
            facet_wrap(~ genotype + uid + replicate, ncol = 4, scales = "free_y") +
            My_Theme
            ggsave(p, filename = "Plot all normalized actograms.png", type = "cairo",height = 33,
       width = 10, dpi = 600, units = "in")    ###############height = 11*n where n is number of genotypes
###############and width = 10
```
### Plot raw profiles for individuals:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = activity,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            facet_wrap(~ genotype + uid + replicate, ncol = 4, scales = "free_y") +
            My_Theme
            ggsave(p, filename = "Plot raw profiles for individuals.png", type = "cairo",height = 33,
       width = 10, dpi = 600, units = "in")    ###############height = 11*n where n is number of genotypes
###############and width = 10
```
### Plot normalized profiles for individuals:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = normact,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            facet_wrap(~ genotype + uid + replicate, ncol = 4, scales = "free_y") +
            My_Theme
            ggsave(p, filename = "Plot normalized profiles for individuals.png", type = "cairo",height = 33,
       width = 10, dpi = 600, units = "in")    ###############height = 11*n where n is number of genotypes
###############and width = 10
```
### Plot daywise raw average profile:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = activity,
              colour = genotype
            ),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            My_Theme
            ggsave(p, filename = "Plot daywise raw average profile.png", type = "cairo",height = 3,
       width = 10, dpi = 600, units = "in")    ###############height = 5*n where n is number of replicates
###############and width = 10
```
### Plot daywise normalized average profile:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = normact,
              colour = genotype
            ),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            My_Theme
            ggsave(p, filename = "Plot daywise normalized average profile.png", type = "cairo",height = 3,
       width = 10, dpi = 600, units = "in")    ###############height = 3*n where n is number of replicates
###############and width = 10
```
### Plot for average profiles - raw:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = activity,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            My_Theme
ggsave(p, filename = "Plot for average profiles - raw.png", type = "cairo",height = 4,
       width = 10, dpi = 600, units = "in")    ###############height = 4*n where n is number of replicates
###############and width = 10
```
### Plot for average profiles - normalized:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = normact,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            My_Theme
ggsave(p, filename = "Plot for average profiles - normalized.png", type = "cairo",height = 4,
       width = 10, dpi = 600, units = "in")    ###############height = 4*n where n is number of replicates
###############and width = 10
```
### Plot average profile all replicates together - raw:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = activity,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            My_Theme
ggsave(p, filename = "Plot average profile all replicates together - raw.png", type = "cairo",height = 4,
       width = 10, dpi = 600, units = "in")
```
### Plot average profile all replicates together - normalized:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = normact,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min),
            time_offset = hours(6)
          ) +
            stat_ld_annotations(
              height = 1,
              alpha = 0.1,
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho() +
            My_Theme
ggsave(p, filename = "Plot average profile all replicates together - normalized.png", type = "cairo",height = 4,
       width = 10, dpi = 600, units = "in")
```
### Plot circular average profile - raw:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = activity,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min)
          ) +
            stat_ld_annotations(
              height = 3,
              alpha = .1,
              x_limits = c(0, hours(24)),
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho(geom = "bar", alpha = 0.4) +
            facet_wrap(~replicate, ncol = 1) +
            My_Theme +
            coord_polar(clip = "off")
ggsave(p, filename = "Plot circular average profile - raw.png", type = "cairo",height = 10,
                                  width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is #############number of replicates
###############and width = 10
```
### Plot circular average profile - normalized:
```
p <- ggetho(
            dt_curated,
            aes(
              x = t,
              y = normact,
              colour = genotype
            ),
            time_wrap = hours(params$modtau),
            summary_time_window = mins(params$min)
          ) +
            stat_ld_annotations(
              height = .3,
              alpha = .1,
              x_limits = c(0, hours(24)),
              outline = NA,
              l_duration = hours(params$light),
              period = hours(params$ldperiod)
            ) +
            stat_pop_etho(geom = "bar", alpha = 0.4) +
            facet_wrap(~replicate, ncol = 1) +
            My_Theme +
            coord_polar(clip = "off")
ggsave(p, filename = "Plot circular average profile - normalized.png", type = "cairo",height = 10,
                                  width = 10, dpi = 600, units = "in")    ###############height = 10*n where n is #############number of replicates
###############and width = 10
```
