is.installed <- function(mypkg) is.element(mypkg, installed.packages()[, 1])


if (!require("shiny")) install.packages("shiny", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("WaveletComp")) install.packages("WaveletComp", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("ggetho")) install.packages("ggetho", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("ggplot2")) install.packages("ggplot2", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("zeitgebr")) install.packages("zeitgebr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("readr")) install.packages("readr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("damr")) install.packages("damr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("sleepr")) install.packages("sleepr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("behavr")) install.packages("behavr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("dplyr")) install.packages("dplyr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinyalert")) install.packages("shinyalert", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("colourpicker")) install.packages("colourpicker", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("beepr")) install.packages("beepr", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("showtext")) install.packages("showtext", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinydashboard")) install.packages("shinydashboard", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinycustomloader")) install.packages("shinycustomloader", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinythemes")) install.packages("shinythemes", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinyWidgets")) install.packages("shinyWidgets", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinyhelper")) install.packages("shinyhelper", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("shinyFiles")) install.packages("shinyFiles", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("fs")) install.packages("fs", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("data.table")) install.packages("data.table", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("Cairo")) install.packages("Cairo", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("pracma")) install.packages("pracma", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("lubridate")) install.packages("lubridate", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("signal")) install.packages("signal", dependencies = TRUE, INSTALL_opts = "--no-multiarch")
if (!require("ggthemes")) install.packages("ggthemes", dependencies = TRUE, INSTALL_opts = "--no-multiarch")

if (is.installed("shiny") & is.installed("WaveletComp") & is.installed("ggetho") & is.installed("ggplot2") & is.installed("zeitgebr") & is.installed("readr") & is.installed("damr") & is.installed("Cairo") & is.installed("ggthemes")
& is.installed("sleepr") & is.installed("behavr") & is.installed("dplyr") & is.installed("shinyalert") & is.installed("colourpicker") & is.installed("beepr") & is.installed("showtext") & is.installed("data.table")
& is.installed("shinydashboard") & is.installed("shinycustomloader") & is.installed("shinythemes") & is.installed("shinyWidgets") & is.installed("shinyhelper") & is.installed("shinyFiles") & is.installed("fs")
& is.installed("signal") & is.installed("lubridate") & is.installed("pracma")) {
  print(paste("Initialisation complete! VANESSA-DAM-CRA is now ready for use"), quote = F)
} else {
  print(paste("Error: One or more packages may not have installed correctly"), quote = F)
}
